name: Deploy to Firebase Hosting on PR
on: pull_request
permissions:
  checks: write
  contents: read
  pull-requests: write
jobs:
  build_and_preview:
    if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      # Setup pnpm
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest
      
      # Setup Node.js with pnpm cache
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      
      # Install dependencies with pnpm
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      
      # Build the project
      - name: Build project
        run: pnpm build
      
      # Deploy to Firebase preview
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_PANMAGALLANES_A39C6 }}
          projectId: panmagallanes-a39c6
        env:
          FIREBASE_CLI_EXPERIMENTS: webframeworks